### ISSUE TITLE
Display impl for Error eats all the useful information

### ISSUE THREAD

**Issue by apoelstra** [hyperium/hyper#694] opened 2015-11-22 19:45 UTC
The Display impl for Error passes through to `std::error::Error::description()`, which is pretty-much useless. For example, all I/O errors become simply "os error" through this lens.

**Comment by seanmonstar** [comment] 2015-11-23 18:32
Fair point. A nice fix here would be to use the description for hyper errors, but delegate to `fmt` of errors from other crates.

Example:

```rust
impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Io(ref e) | Uri(ref e) | Ssl(ref e) | Http2(ref e) | Utf8(ref e) => fmt::Display::fmt(e, f),
            e => f.write_str(e.description())
        }
    }
}

```

**Comment by apoelstra** [comment] 2015-11-24 17:27
Yeah, I'd be happy with that.

**Comment by sfackler** [comment] 2015-12-19 00:29
I tend to go with something like

```rust
impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        try!(f.write_str(self.description())
        match *self {
            AllThingsWithInnerErrors(ref e) => write!(f, "{}", e),
            ....
        }
    }
}
```

**Comment by seanmonstar** [comment] 2015-12-19 00:54
With https://github.com/rust-lang/rust/pull/30312 being merged, at this should state something more than `os error` in Rust 1.7, which is an improvement...

**Comment by xaviershay** [comment] 2016-02-20 17:07
I'm getting conflicting messages from this thread. If the problem is that `os error` isn't useful, that's coming from `fmt` of a _non-hyper_ IO error. So handing off error formatting of non-hyper errors (such as `IO`) to `fmt` wouldn't actually address the initial example. Right?

**Comment by apoelstra** [comment] 2016-02-20 17:50
@xaviershay the problem is that a `Display` impl is calling `description` on the std error instead of `Display::fmt`, so no useful information is propagated, even though it's accessible from the std error.

**Comment by seanmonstar** [comment] 2016-02-22 19:11
@xaviershay it's because the `description` of `io::Error` before Rust 1.7 simply says "os error". Instead of printing the description, we could print the full `fmt::Debug` message of `io::Error` (or, in 1.7, the description will match the Debug output anyways).

**Comment by josephpd3** [comment] 2016-05-19 03:42
Hey all, I am a little confused on this issue. @seanmonstar, did your PR [rust-lang/rust#30312](https://github.com/rust-lang/rust/pull/30312) resolve the matter or am I not quite understanding? Apologies, I'm still getting used to Rust and would like to help if I can.

**Comment by seanmonstar** [comment] 2016-05-19 18:37
@josephpd3 I'm sure that PR improved things. We could make it a little better in hyper by doing as I suggest in the [2nd comment](https://github.com/hyperium/hyper/issues/694#issuecomment-159021620).

**Closed** 2016-06-20 15:08 UTC
Labels: easy
