### ISSUE TITLE
Panic when getting empty response from server

### ISSUE THREAD

**Issue by jpgneves** [hyperium/hyper#646] opened 2015-09-04 07:26 UTC
As noted in this other (closed) issue: https://github.com/hyperium/hyper/issues/365

When receiving empty response data, hyper consistently panics with:

```
thread '<unnamed>' panicked at 'thread '<unnamed>Http11Message lost its underlying stream somehow.', /home/jneves/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.10/src/http/h1.rs:270
```

**Comment by seanmonstar** [comment] 2015-09-04 16:04
Yep, try updating hyper, this was fixed in a patch.

**Comment by mlalic** [comment] 2015-09-04 22:42
Actually, I think this can happen, but not because the response is empty, but because the `Content-Length` header is invalid.

For example, try accessing a server that gives `Content-Length: asdf` or even `Content-Length: ` (i.e. empty) and you'll reproduce this.

It's because the `get_incoming` method definitely drops the stream [here](https://github.com/hyperium/hyper/blob/32e09a04292b0247456a8fb9003a75a6abaa998e/src/http/h1.rs#L227-L228) and returns an `Err`, but then `Response` tries closing it in the error match arm [here](https://github.com/hyperium/hyper/blob/32e09a04292b0247456a8fb9003a75a6abaa998e/src/client/response.rs#L42).

Adding a line to save the stream before returning the `Err` in `get_incoming` fixes it, though...

**Closed** 2015-09-04 23:33 UTC
