### ISSUE TITLE
Are Android and iOS supported by hyper?

### ISSUE THREAD

**Issue by kingofoz** [hyperium/hyper#1308] opened 2017-09-07 09:21 UTC
Thanks.

**Comment by seanmonstar** [comment] 2017-09-07 16:46
Hi there! I believe so, yes. Servo uses hyper, and builds for Android.

As this is a question and not a bug, I'm going to close this.

**Closed by seanmonstar** 2017-09-07 16:46 UTC

**Comment by kingofoz** [comment] 2017-09-08 07:01
Thanks, @seanmonstar
