### ISSUE TITLE
Invalid chunk size line

### ISSUE THREAD

**Issue by TheFreakLord** [hyperium/hyper#1146] opened 2017-04-20 18:05 UTC
I'm using rocket (which is using hyper) and whenever I access a POST route taking some multiform data from localhost (so it's localhost->localhost) I get an error complaining about an invalid chunk size line. When I run the server-part on a different machine (a generic chinese pi clone, ARMv7) everything works as expected.

I'm not sure what's causing the error, but I were told that it is most likely something with hyper so I'm reporting this here.

Also, here's a log I got from my testing: https://paste.niobium.me/view/5481d79c

**Comment by seanmonstar** [comment] 2017-04-20 23:10
An invalid chunk size means the stream was encoded with the chunked transfer encoding, and then trying to decode, it found a chunk header to be invalid. Your log output shows that there was a panic in Rocket, which I've found to be this line: https://github.com/SergioBenitez/Rocket/blob/v0.2.6/lib/src/data/data_stream.rs#L44

That should not be a call to `expect`.

**Comment by SergioBenitez** [comment] 2017-04-21 17:50
It's certainly not very graceful to call `expect` there. I've mended this in https://github.com/SergioBenitez/Rocket/commit/1e5a1b89409feb827b0d1ee20525191d17ad5c13. Unfortunately, I don't think this will solve @TheFreakLord's issue.

@TheFreakLord Can you post the full HTTP Request that's causing the problem? This will help determine if the request is valid and we can move forward from there.

**Comment by seanmonstar** [comment] 2017-04-21 20:03
@SergioBenitez I was reading through the `data.rs` file in Rocket, and I may have found a possible cause. It looks like the buffer is taken from hyper, and a new `HttpReader` is constructed. Since its chunked encoding, and never been read before, it becomes a `ChunkedReader(stream, None)`. There's 2 issues here, the second is where the error is coming from:

1. hyper's original stream is a `HttpReader<BufReader>`, to allow 1 syscall to buffer the contents, and then `ChunkedReader` can make smaller reads looking for the chunk header. By taking the buffer, the `Data` now has a bunch of raw chunked data that hasn't been decoded, so now reads on the `DataStream` will include the chunked encoding bytes.
2. Once the buffer in the `Data` has been read through, it delegates to the `ChunkedReader<NetworkStream>` to read. At this point, it currently thinks chunk size is `None`, so it is going to try to find the chunk size in the next bytes. However, looking at the contents of the buffer from the pastebin, the end of the buffer is an 8192 length chunk, followed by 3765 bytes. On the network, there should still be 4427 bytes to read, but the `ChunkedReader` doesn't know. The next bytes of the PNG aren't a chunk header, and so it errors.

**Comment by seanmonstar** [comment] 2017-04-21 21:15
I'm going to close this, as it sounds like the issue is specific to Rocket, but if any other issues do occur that are specific to hyper, we can file more!

**Closed by seanmonstar** 2017-04-21 21:15 UTC

**Comment by TheFreakLord** [comment] 2017-04-22 16:54
I'm still confused why this only happens when doing local tests. It doesn't happen when the server is running on a separate machine.

**Comment by seanmonstar** [comment] 2017-04-22 17:45
On the separate machine, are you still using chunked transfer encoding, or is a content length set? And is the file the same size? Or less than 4kb?
