### ISSUE TITLE
Stabilize some of the foundational types in a separate crate

### ISSUE THREAD

**Issue by dtolnay** [hyperium/hyper#1196] opened 2017-05-31 04:31 UTC
The current situation is:

- Reqwest would like to release a stable version.
- Currently reqwest re-exports the Method, StatusCode, and HttpVersion types from hyper, so it couldn't be stable until hyper is stable.
- Stable hyper is waiting on stable tokio.
- Stable tokio is not imminent.

Let's extract these foundational types into a separate crate that we can stabilize sooner than all of hyper.

**Comment by theduke** [comment] 2017-05-31 21:29
I would suggest to try and use the `http` crate name for this. 

It already exists,  https://crates.io/crates/http , but the owner could hopefully persuaded to give it up.

**Comment by seanmonstar** [comment] 2017-05-31 21:51
Yes, we would. We've been in contact with the owner, he specifically reserved it for just such an effort.

However, it's probably a bit ambitious to stabilize an `http` crate super quickly, so for reqwest, it will likely just define its own types, and we'll hope that an eventual `http` crate mirrors what it has.

**Comment by jimmycuadra** [comment] 2017-06-02 01:11
Possible dupe of https://github.com/hyperium/hyper/issues/894?

**Comment by seanmonstar** [comment] 2017-06-02 19:12
Yes, dupe, so I'm going to close. There's issues opened in reqwest crate about implementing those primitives there.

**Closed by seanmonstar** 2017-06-02 19:12 UTC
