### ISSUE TITLE
Hello app hangs after 16333 requests

### ISSUE THREAD

**Issue by 13h3r** [hyperium/hyper#1314] opened 2017-09-09 13:45 UTC
Hey!

I run hello example and app stop responding after 16333 requests.

Built with `cargo build` (both debug and release), run with `ab  -n 20000 http://127.0.0.1:3000/`. Output of ab:

```
» ab  -n 20000 http://127.0.0.1:3000/                                                                        60 ↵
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
apr_socket_recv: Operation timed out (60)
Total of 16333 requests completed
```

This is 100% reproducible on my mac. After some time (10 seconds) app is responding again.

Is it expected behaviour or bug? How could I reconfigure this hello app to get rid of this?

Thanks!

Cargo.toml
```
[dependencies]
hyper = "0.11"
futures = "0.1.15"
```

main.rs
```rust
extern crate hyper;
extern crate futures;


use hyper::header::ContentLength;
use hyper::server::{Http, Request, Response, Service};

struct HelloWorld;

const PHRASE: &'static str = "Hello, World!";

impl Service for HelloWorld {
    // boilerplate hooking up hyper's server types
    type Request = Request;
    type Response = Response;
    type Error = hyper::Error;
    // The future representing the eventual Response your call will
    // resolve to. This can change to whatever Future you need.
    type Future = futures::future::FutureResult<Self::Response, Self::Error>;

    fn call(&self, _req: Request) -> Self::Future {
        // We're currently ignoring the Request
        // And returning an 'ok' Future, which means it's ready
        // immediately, and build a Response with the 'PHRASE' body.
        futures::future::ok(
            Response::new()
                .with_header(ContentLength(PHRASE.len() as u64))
                .with_body(PHRASE)
        )
    }
}

fn main() {
    let addr = "127.0.0.1:3000".parse().unwrap();
    let server = Http::new().bind(&addr, || Ok(HelloWorld)).unwrap();
    server.run().unwrap();
}
```

**Comment by seanmonstar** [comment] 2017-09-11 18:39
When I start the hello world example, I can run wrk against it, and get way passed 16000 requests (I stopped at 200,000). Does it happen to you if you use wrk also?

Also, I don't have a Mac, so I'm running these tests on Ubuntu.

**Comment by 13h3r** [comment] 2017-09-11 19:29
I tried to run this on ubuntu vpc and it works fine with `ab`.
I tried `wrk` on mac and it also works fine. The only difference between `ab` and `wrk` is connection management. `ab` open new connection every time and `wrk` reuse existing once. Do you have any ideas to check to verify connection management problem here?

**Comment by seanmonstar** [comment] 2017-09-11 19:35
Ah, I didn't realize ab makes a new connection per request. In that case, it might be that you're hitting a max file descriptor limit on your Mac.

**Comment by 13h3r** [comment] 2017-09-11 19:47
I did `ulimit -a 32000` and set kernel params to corresponding values.

**Comment by seanmonstar** [comment] 2017-09-11 20:24
And what's the outcome?

**Comment by 13h3r** [comment] 2017-09-11 20:56
Sorry for not mentioning this. Same problem. App hangs after 16k connections

**Comment by seanmonstar** [comment] 2017-09-11 21:12
A google search suggests doing this for macOS: https://stackoverflow.com/questions/7578594/how-to-increase-limits-on-sockets-on-osx-for-load-testing

As this seems to be Mac specific, and not a bug in hyper, I'm going to close the issue.

**Closed by seanmonstar** 2017-09-11 21:12 UTC
