### ISSUE TITLE
keep_alive not response with header Connection: 

### ISSUE THREAD

**Issue by july2993** [hyperium/hyper#1393] opened 2017-11-30 08:25 UTC
with a  Http server set keep_alive to true, and use ab (-k to set keep-alive) to test

```
➜   git:(master) ✗ ab   -k -v 4 -c 1 -n 1 http://127.0.0.1:8080/bar
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...INFO: GET header ==
---
GET /bar HTTP/1.0
Connection: Keep-Alive
Host: 127.0.0.1:8080
User-Agent: ApacheBench/2.3
Accept: */*


---
LOG: header received:
HTTP/1.1 406 Not Acceptable
Content-Length: 42
Date: Thu, 30 Nov 2017 04:56:01 GMT

{"error": "invalid digit found in string"}
WARNING: Response code not 2xx (406)
apr_pollset_poll: The timeout specified has expired (70007)
```

ab will hang, because it is expected to receive the Connection header and check it.
i add a connection header myself in the response to address the problem, but i think hyper should better add the header automatically， or it is supposed to be add by youself as expected?
some ref i found: [draft-ietf-http-v11-spec](https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01.html#Persistent%20Connections)

**Comment by sfackler** [comment] 2017-11-30 17:08
HTTP/1.1 connections are assumed to be kept alive unless otherwise stated with a `Connection: close`: https://tools.ietf.org/html/rfc7230#section-6.3.

Why do you think it's trying to read a Connection header? It's already read past the headers into the body, so more headers are definitely not going to be sent.

**Comment by sfackler** [comment] 2017-11-30 17:09
Ah, the issue is that ab is sending an HTTP/1.0 request but Hyper's responding with an HTTP/1.1 response. I think this is the same as https://github.com/hyperium/hyper/issues/1304.

**Comment by july2993** [comment] 2017-12-01 07:28
thanks for you reply, it's the same as #1304  i even did'n notice that ab send HTTP/1.0 😢  .

**Comment by seanmonstar** [comment] 2017-12-01 22:26
Yep, this is #1304. Closing as duplicate.

**Closed by seanmonstar** 2017-12-01 22:26 UTC
