### ISSUE TITLE
direct Unix-domain-socket support like the "hyperlocal" crate

### ISSUE THREAD

**Issue by njaard** [hyperium/hyper#1633] opened 2018-08-14 15:58 UTC
The [Hyperlocal](https://docs.rs/hyperlocal) crate allows a hyper server that listens on unix domain sockets. I find it essential because I use hyper proxied behind an nginx proxy. I prefer proxying from a service on a unix domain socket because then I can use the "native" namespace as opposed to maintaining my own list of ip addresses.

If I want my server to support `unix:` address prefixes, then I need to code to choose between a hyper's TCP and hyperlocal's socket spawner. And as a result, I need to understand all the `Server`-related traits to create a function that can do that.

**Comment by seanmonstar** [comment] 2018-08-14 17:27
hyper's `Server` can be constructed with any sort of "incoming" stream of connections, such as what hyperlocal provides. Considering this flexibility, and that using unix domain sockets isn't actually the common case, it has seemed sufficient to leave this functionality outside of the hyper crate. I'm going to close this, as essentially a duplicate of #126.

**Closed by seanmonstar** 2018-08-14 17:27 UTC

**Comment by njaard** [comment] 2018-08-14 18:27
I would normally agree, but fashioning a function that accepts a service and returns an appropriate (Boxed?) server based on what the address looks like is really difficult for someone who doesn't have an exceptionally good understanding of tokio and hyper's types.

At least there should be an example (or pre-baked) function for this in hyperlocal (for which this isn't the right place).

Also, people might be more inclined to use this feature if they knew how :)

**Comment by njaard** [comment] 2018-11-04 01:47
> hyper's Server can be constructed with any sort of "incoming" stream of connections, such as what hyperlocal provides

*Maybe* this statement is technically true, but it is still **impossible** to properly implement something like "hyperlocal", as "hyperlocal" demonstates, by not actually functioning correctly.

One cause seems to be that to replicate the functionality Hyper already has with Tcp sockets but instead with Unix Domain Sockets, one would need to have a copy of pretty much all of `hyper/src/server` and `hyper/src/common` (at least), since most of those are used by hyper's TCP support, and most of those are private symbols.
