### ISSUE TITLE
Broken pipe error with hyper::Client

### ISSUE THREAD

**Issue by bachm** [hyperium/hyper#1403] opened 2017-12-23 08:54 UTC
I built a client following the [client guides](https://hyper.rs/guides/client/basic) and tend to get a broken pipe error. I'm copying the guides as closely as possible.

`Hyper(Io(Error { repr: Custom(Custom { kind: BrokenPipe, error: StringError("broken pipe") }) }))`

The code that's generating the error:

```     
        // uri is a https address
        let work = self.client.get(uri).and_then(|res| {
            res.body().concat2()
        });
        
        let response = self.core.run(work)?;
```
self in the above code refers to this struct

```
pub struct Client {
    core: Core,
    client: hyper::Client<HttpsConnector<HttpConnector>>,
}
```
which is constructed like this 

```
pub fn new() -> Self {
        let core = Core::new().expect("failed to create Core");
        let handle = core.handle();
        let client = hyper::Client::configure()
            .connector(HttpsConnector::new(4, &handle)
            .expect("https connector"))
            .build(&handle);
        Client {
            core,
            client,
        }
    }
```

**Comment by kamyuentse** [comment] 2017-12-23 16:57
Check [reqwest](https://github.com/seanmonstar/reqwest) for ergonomic HTTP Client in Rust.

**Comment by seanmonstar** [comment] 2017-12-26 20:23
Do it always happen, or only on certain URLs? Is there a request body, or a large response body? Is it possible to turn on logs for hyper?

If adventurous, you could try enabling `no_proto` on the client config, which has some fixes that may include this. It will become default soon, but might contain other bugs...

**Comment by seanmonstar** [comment] 2018-01-08 18:10
Does this still happen? With the release of v0.11.11, the internal dispatcher for the client has been redone, and many bugs were fixed, which I *think* includes this one.

**Comment by seanmonstar** [comment] 2018-01-12 19:28
I'm going to close this, since I don't know how to reproduce, and am hopeful that the bugs fixed with the new dispatcher fixed this as well. If not, we can re-open!

**Closed by seanmonstar** 2018-01-12 19:28 UTC
