### ISSUE TITLE
swagger-codegen hyper 0.12 code review

### ISSUE THREAD

**Issue by ctaggart** [hyperium/hyper#1933] opened 2019-09-09 15:19 UTC
It would be wonderful if I could get a code review of https://github.com/swagger-api/swagger-codegen/pull/9699. It upgrades the swagger-codegen templates for rust (client) from hyper 0.11.6 to 0.12.34. I have several questions.

For example, I ended up using `hyper_old_types` crate. Is there a better way that doesn't use that crate to do:

https://github.com/swagger-api/swagger-codegen/pull/9699/files#diff-0e0813a48d274c975e43b4122db95381R73-R77

**Comment by seanmonstar** [comment] 2019-09-11 17:50
Cool!

> I have several questions.

I can try to answer them. You can also try [Gitter chat](https://gitter.im/hyperium/hyper) if you want perhaps faster answers. (Though at the same time, I'm going to close the issue since it's not a bug in hyper :D).

>  I ended up using hyper_old_types crate. Is there a better way that doesn't use that crate to do:

There is the [headers](https://crates.io/crates/headers) crate which the (slow) evolution of the typed headers. It's missing some constructors, so it hasn't really been shown off much, but I believe `Authorization::bearer` works in your case.

**Closed by seanmonstar** 2019-09-11 17:50 UTC
