### ISSUE TITLE
SOCKS support // Service composability

### ISSUE THREAD

**Issue by teythoon** [hyperium/hyper#1445] opened 2018-02-20 11:10 UTC
We need SOCKS support in order to use TOR, and I'm not sure how to do that using the current version of hyper.  I have found https://github.com/sfackler/rust-hyper-socks, but it depends on being able to hand TcpStreams to hyper.

Aiui the way to do that in contemporary versions is to implement the Service trait, so I looked into that.  I believe that I could implement SOCKS support this way, but it would require duplicating a lot of the code that is in hyper proper.  So that makes me wonder whether it is possible (or should be possible) to compose Services in a way that I'm missing.

Could you please clarify that?

**Comment by seanmonstar** [comment] 2018-02-20 22:01
To clarify, are you trying to add support to a client, or a server?

For a client, it is able to use any `Connect` type to receives IO transports to run HTTP over.

```rust
let client = Client::configure()
    .connector(SocksConnector::new())
    .build(&handle);
```

 For the server, that `Service` layer has nothing to do with the underlying transport. You can accept a socket however you like, and then bind a server connection to a service using [`Http::serve_connection`](https://docs.rs/hyper/0.11.18/hyper/server/struct.Http.html#method.serve_connection).

**Comment by teythoon** [comment] 2018-02-21 09:24
We need SOCKS support in the client.  I realize how to use a custom connector, my question rather is if I (or someone else) implements a `SocksConnector`, does she have to duplicate the functionality of `client::HttpConnector` or can one somehow compose the `Service`s to avoid duplication.

**Comment by seanmonstar** [comment] 2018-02-21 20:40
Yes, you can certainly combine connectors. Take a look at how [hyper-tls does it](https://github.com/hyperium/hyper-tls/blob/master/src/client.rs). It by default just uses `hyper::client::HttpConnector`, but is actually generic over any, allowing someone to wrap any connector with TLS.

(I'm going to close this since this seems to be a usage question and not a bug in hyper.)

**Closed by seanmonstar** 2018-02-21 20:40 UTC

**Comment by teythoon** [comment] 2018-02-22 11:31
So I started implementing this, and as anticipated I'm at the point of more or less completely copying hyper/client/connect.rs.  So either I'm still confused (very well possible), or you pointed me in the wrong direction.

hyper-tls uses `hyper::client::HttpConnector`, or any other connector, like the proposed `SocksConnector`.  That is nice, but that is in fact the other direction (layering Services on top of say `hyper::client::HttpConnector`).

My question was whether and how it is possible to make `hyper::client::HttpConnector` use the `SocksConnector` to establish a TCP connection.

**Comment by seanmonstar** [comment] 2018-02-22 23:30
Oh, sorry, I assumed you could use `HttpConnector` internally to do the DNS resolution and get a TcpStream back, and then do the SOCKS negotiation on that stream.

The `HttpConnector` doesn't have much that you can plug into it...

**Comment by sfackler** [comment] 2018-02-22 23:41
Can't you just make a URI to the proxy and use HttpConnector to connect to it?

**Comment by jbg** [comment] 2018-06-25 10:24
what would that URI look like? (the question is about SOCKS proxies, not HTTP proxies)
