### ISSUE TITLE
Strange behaviour of server with HTTP keep-alive connection

### ISSUE THREAD

**Issue by izderadicka** [hyperium/hyper#1590] opened 2018-07-02 09:13 UTC
I used the provided send_file example with apache benchmark (ab). As ab is using HTTP 1.0 I modified example and  add Connection: keep-alive header as shown below:

```rust
fn simple_file_send(f: &str) -> ResponseFuture {
    // Serve a file by asynchronously reading it entirely into memory.
    // Uses tokio_fs to open file asynchronously, then tokio_io to read into
    // memory asynchronously.
    let filename = f.to_string(); // we need to copy for lifetime issues
    Box::new(tokio_fs::file::File::open(filename)
        .and_then(|file| {
            let buf: Vec<u8> = Vec::new();
            tokio_io::io::read_to_end(file, buf)
                .and_then(|item| {
                    let res = Response::builder()
                    .header(hyper::header::CONNECTION, "keep-alive")
                    .body(item.1.into())
                    .unwrap();    
                    Ok(res)
                })
                .or_else(|_| {
                    Ok(Response::builder()
                        .status(StatusCode::INTERNAL_SERVER_ERROR)
                        .body(Body::empty())
                        .unwrap())
                })
        })
        .or_else(|_| {
            Ok(Response::builder()
                .status(StatusCode::NOT_FOUND)
                .body(NOTFOUND.into())
                .unwrap())
        }))
}
```

Then I use this command:
```
ab  -n 10 -c 1  -k  http://localhost:1337/
```

For default provided file everything went ok, however for bigger file - ~ 90K I got problems:

```
ab  -n 10 -c 1  -k  http://localhost:1337/
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)...apr_pollset_poll: The timeout specified has expired (70007)
Total of 5 requests completed
```

For more requests ab breaks after 10 failures

I was looking with wireshark into TCP packets, but I'm no expert, but noticed this:
- for smaller file, where everything worked, both request and response fit into one package
- for bigger file responses were split between several packets, also I've seen there several connection resets

I run example server as:
```
cargo run --release --example send_file
```

My platform is linux Ubuntu 16.04 64 bits.
Compiled with rustc 1.28.0-nightly (84804c387 2018-06-26)
hyper is current clone of master branch

I used ab previously in some tests, it looks like reliable tool to me.

**Comment by seanmonstar** [comment] 2018-07-02 17:10
Would you be able to capture the request and response headers? Bonus points if you could capture the logs from hyper (like using env_logger with `RUST_LOG=hyper`).

As for a benchmark tool, I have actually had problems with ab. I personally find [wrk](https://github.com/wg/wrk) to be much better.

**Comment by izderadicka** [comment] 2018-07-02 19:01
headers:

```
GET / HTTP/1.0
Connection: Keep-Alive
Host: localhost:1337
User-Agent: ApacheBench/2.3
Accept: */*

```

```
HTTP/1.0 200 OK
connection: keep-alive
content-length: 88652
date: Mon, 02 Jul 2018 08:52:48 GMT

```

**Comment by izderadicka** [comment] 2018-07-02 19:08
Log:
```
 TRACE hyper::proto::h1::conn > Conn::read_head
 TRACE hyper::proto::h1::conn > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy, error: None }
 TRACE hyper::proto::h1::conn > Conn::read_head
 DEBUG hyper::proto::h1::io   > read 106 bytes
 TRACE hyper::proto::h1::role > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io   > parsed 4 headers
 DEBUG hyper::proto::h1::conn > incoming body is empty
 TRACE hyper::proto::h1::conn > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::io   > flushed 88755 bytes
 DEBUG hyper::proto::h1::io   > read 106 bytes
 TRACE hyper::proto::h1::conn > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle, error: None }
 TRACE hyper::proto::h1::conn > Conn::read_head
 TRACE hyper::proto::h1::role > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io   > parsed 4 headers
 DEBUG hyper::proto::h1::conn > incoming body is empty
 TRACE hyper::proto::h1::conn > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::dispatch > error writing: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Connection reset by peer (os error 104)
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::io          > flushed 88755 bytes
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::dispatch    > error writing: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Connection reset by peer (os error 104)
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::io          > flushed 88755 bytes
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::io          > flushed 88755 bytes
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::dispatch    > error writing: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Connection reset by peer (os error 104)
 DEBUG hyper::proto::h1::dispatch    > error writing: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Connection reset by peer (os error 104)
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::io          > flushed 88755 bytes
 DEBUG hyper::proto::h1::io          > read 106 bytes
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle, error: None }
 TRACE hyper::proto::h1::conn        > Conn::read_head
 TRACE hyper::proto::h1::role        > Request.parse([Header; 100], [u8; 106])
 TRACE hyper::proto::h1::role        > Request.parse Complete(106)
 DEBUG hyper::proto::h1::io          > parsed 4 headers
 DEBUG hyper::proto::h1::conn        > incoming body is empty
 TRACE hyper::proto::h1::conn        > read_keep_alive; is_mid_message=true
 TRACE hyper::proto::h1::role        > Server::encode status=200, body=Some(Known(88652)), req_method=Some(GET)
 DEBUG hyper::proto::h1::dispatch    > error writing: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Connection reset by peer (os error 104)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Connection reset by peer (os error 104)
```

I'll try wrk tomorrow

**Comment by seanmonstar** [comment] 2018-07-02 19:10
> for bigger file responses were split between several packets, also I've seen there several connection resets

Ah OK, so yes, with a ~90KB file, it will be sent over multiple packets (frequent packet size is much smaller, around 4-8KB).

I re-read your original message, and noticed you're seeing timeouts. What's the timeout that ab is waiting? Is it shorter than it takes to read the full file from disk?

**Comment by izderadicka** [comment] 2018-07-02 19:18
@seanmonstar  - if you mean timeout reported by ab, then it's takes likes 20-30 secs and then tests ends. Definitely more then to read the file.

**Comment by izderadicka** [comment] 2018-07-03 09:31
Hi, 
I tried wrk - it seems to work better (it uses HTTP 1.1 where keep alive is by default) , but it does not report failed requests, but throughput looks reasonable.

Sometimes I see these errors in log, when wrk is ending. But I guess it might be wrk problem as it can close connections on test end and not wait for response.
```
TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Closed, writing: Init, keep_alive: Disabled, error: None }
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Broken pipe (os error 32)
 TRACE hyper::proto::h1::conn        > flushed({role=server}): State { reading: Closed, writing: Init, keep_alive: Disabled, error: None }
 DEBUG hyper::proto::h1::dispatch    > error writing: Broken pipe (os error 32)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::proto::h1::dispatch    > error writing: Broken pipe (os error 32)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::proto::h1::dispatch    > error writing: Broken pipe (os error 32)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::proto::h1::dispatch    > error writing: Broken pipe (os error 32)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::server::conn::upgrades > error polling connection protocol: error writing a body to connection: Broken pipe (os error 32)
 DEBUG hyper::server::conn           > conn error: error writing a body to connection: Broken pipe (os error 32)
```

**Comment by seanmonstar** [comment] 2018-07-10 20:45
I can't see anything that suggests the issue is in hyper. It seems the tools are just closing connections. If I'm wrong, and an issue is identified, we can re-open!

**Closed by seanmonstar** 2018-07-10 20:45 UTC
