### ISSUE TITLE
Body stream parsing progress blocked for response size > INIT_BUFFER_SIZE

### ISSUE THREAD

**Issue by valeriansaliou** [hyperium/hyper#1260] opened 2017-07-14 10:46 UTC
Hi!

Trying to consume a `response.body()` from Hyper client, and convert response body to a String.

Works great overall with the code below for small responses. **When the number of chunks is greater than 1, the second chunk never comes in** to the stream as I would expect (`wait()` is used only for the example below).

**Hyper version:** `0.11.1`
**Rust version:** `nightly`
**OS:** `macOS 10.12.5`

```rust
let body_result = res.body()
    .map_err(|_| {
        debug!("==> ERROR");

        ()
    })
    .map(|chunk| {
        debug!("==> CHUNK");

        chunk
    })
    .fold(Vec::new(), |mut vector, chunk| {
        debug!("==> FOLD");

        vector.extend_from_slice(&chunk);

        debug!("==> CONVERTED: {:?}", String::from_utf8(chunk.to_vec()).unwrap());

        Ok(vector)
    })
    .and_then(|vector| {
        debug!("==> FOLDED");

        String::from_utf8(vector).map_err(|_| ())
    })
    .wait();
```

**Code reference:** [valeriansaliou/bloom/blob/master/src/cache/write.rs#L35](https://github.com/valeriansaliou/bloom/blob/master/src/cache/write.rs#L35) (still using `wait()`, gotta change this, I'm aware of the issues w/ the event loop).

Debug breakpoints have been added in the code above to follow the stream chunks as they come.

When the response body UTF-8 size is less than approx. `INIT_BUFFER_SIZE` — which is ~8KB ([hyperium/hyper/blob/ecd4c860a38179a8cba65700bc471aef0bdc599d/src/http/io.rs#L12](https://github.com/hyperium/hyper/blob/ecd4c860a38179a8cba65700bc471aef0bdc599d/src/http/io.rs#L12)), the stream resolves to a String properly.

However, when the response body is larger than `INIT_BUFFER_SIZE` (eg. in my case it is ~20KB), the first chunk comes as expected (approx. 8KB), but the next chunk isn't received in the stream handler, thus the `wait()` blocks indefinitely.

Is there any issue there or something I omitted? Looking at `http/io.rs` I see some blocking involved when chunk max. size is exhausted for buffer — still a beginner in Rust so maybe I'm mis-understanding something.

**Comment by seanmonstar** [comment] 2017-07-14 17:46
Are you sure it has this problem if you remove all `wait`s from your code? I'm fairly confident it is the `wait`. 

The reason is this: tokio currently eagerly caches the first body chunk. If the body is small, and could fit in 1 chunk, then after receiving it, the body stream will yield empty, and the `wait` will be able to finish without ever parking the thread.

However, if the body needs more than 1 read, then after the `wait` polls for the first chunk, and sees it needs to wait for more, it will park the thread. That thread will completely pause, until the something tells it that the future is ready again. The problem is that the very same thread is needed to keep reading on the socket, and alert the `wait` when more data has been found.

-----

Separately, you can use `Stream::concat2` (so, `body.concat2()`) to accomplish the same thing your `fold` is doing.

**Comment by valeriansaliou** [comment] 2017-07-14 20:24
Thanks 👍 , looking into it. Will get back with a solution to share.

**Comment by ampotos** [comment] 2017-07-18 12:30
Hi,
I have a similar issue, did you find any solution ?

**Comment by valeriansaliou** [comment] 2017-07-18 12:36
Hi! Still on it. Didn't have much time over the last days to work on it.

**Comment by ampotos** [comment] 2017-07-18 13:12
Ok.
If it can help the same behavior happen when 2 thread are doing the same request almost at the same time. The second start when the first didn't finish to wait, in this case the first thread never wake up.

I'm new to rust so I can try to help but I'm not sure to be really useful.

**Comment by seanmonstar** [comment] 2017-07-27 20:52
I believe the issue is using `wait` on the same thread as the `Core` is running, so I'm going to close this. If you find otherwise, we can re-open!

**Closed by seanmonstar** 2017-07-27 20:52 UTC

**Comment by ivanovaleksey** [comment] 2018-06-24 23:08
Hello @seanmonstar, it seems I faced with the similar issue while trying to build a client.
I make everything as in [the example](https://github.com/hyperium/hyper/blob/master/examples/client.rs) though my application is just hanging up and waiting for something.
I guess it is very stupid question but what it is a common way to organize the things to avoid "using wait on the same thread as the Core is running".
