### ISSUE TITLE
client blocks even when timeout is set

### ISSUE THREAD

**Issue by chenhouwu** [hyperium/hyper#980] opened 2017-01-01 12:58 UTC
I am a user of `hyper 0.9.x`, and suffers the blocking issue for a long time without any solution after googling a lot. the code sample is here:

```rust
fn create_hyper_client() -> Client {
    let delay = Duration::from_secs(10);
    let mut client = Client::new();
    client.set_read_timeout(Some(delay));
    client.set_write_timeout(Some(delay));
    client
}

fn foo(){
    let mut res = {
        let mut headers = Headers::new();
        headers.set_raw("Content-Type",
                        vec![b"application/x-www-form-urlencoded"
                        .to_vec()]);
        headers.set_raw("Accept", vec![b"application/json".to_vec()]);

        let client = low::create_hyper_client();
        let url = format!("https://xxxx.com/api/v2/{}", cmd);
        Ok(try!(client.post(url.as_str())
                .body(&signed_query)
                .headers(headers)
                .header(Connection::close())
                .send()))
    }
    let mut payload = String::new();
    try!(res.read_to_string(&mut payload));
}
```

If the server or the connection are unstable, the program have chances to be blocked and never go through, so I have to kill & restart.

Anything I should be careful for to avoid the situation?

**Comment by seanmonstar** [comment] 2017-01-01 18:21
Most likely, it is the DNS resolution that is blocking for a long time. The
current usage of std::net does not allow for a timeout. This is solved in
the unreleased 0.10 version, but unfortunately there isn't anything you can
really do right now.

**Comment by chenhouwu** [comment] 2017-01-01 18:29
Seems not caused by DNS, because the stability of my program varies quite much for different api vendors. When the api server have stability issue (can be seen from web pages), my program blocks more often than normal. The api server from another vendor rarely blocks, yes, but still has little chance to block.

**Comment by seanmonstar** [comment] 2017-01-01 19:09
It could possibly be the `connect` operation not timing out. That would be after DNS, where `TcpStream::connect` is trying to do the initial TCP handshake, and it also does not listen to a timeout.

The stages a request goes through:

1. DNS (no timeout in std::net)
2. Connect (no timeout in std::net)
3. set_read_timeout, set_write_timeout (uses setsockopt)
4. Normal IO (uses sockopt timeouts)

**Comment by chenhouwu** [comment] 2017-01-02 00:06
resonable. So.....since the std lib don't provide timeout, I have no means to overcome it only if to use thread control or async io?

**Comment by theduke** [comment] 2017-01-02 00:09
@chenhouwu I have the same issue.

Very annoying. Since you can't kill a thread externally, the only workaround I see right now is to run the client in a thread. In the main thread I check for a timeout, mark the thread as stale, and try again in a new thread. 

Horrible solution of course, but sufficient for my current problem.

**Comment by chenhouwu** [comment] 2017-01-02 00:12
I will shift to rust-curl, @theduke

**Comment by theduke** [comment] 2017-01-02 00:16
@chenhouwu  yeah I'll have to do the same in the medium term...

**Comment by seanmonstar** [comment] 2017-01-02 02:30
In the medium term, a new version using async IO (and thus timeouts on everything) should be released.

For now, closing as duplicate of #721

**Closed by seanmonstar** 2017-01-02 02:30 UTC
