### ISSUE TITLE
How to construct a custom Executor?

### ISSUE THREAD

**Issue by Hexilee** [hyperium/hyper#2117] opened 2020-01-27 17:34 UTC
As `hyper::common::Exec` is private.

**Comment by sfackler** [comment] 2020-01-27 17:35
You implement the public Executor trait: https://docs.rs/hyper/0.13.1/hyper/rt/trait.Executor.html

**Comment by Hexilee** [comment] 2020-01-27 17:46
```rust
use hyper::rt;
use std::future::Future;
use std::pin::Pin;

type ExFuture = Pin<Box<dyn Future<Output = ()> + Send>>;

#[derive(Copy, Clone)]
pub struct Executor;

impl rt::Executor<ExFuture> for Executor {
    fn execute(&self, fut: ExFuture) {
        async_std::task::spawn(Box::pin(fut));
    }
}
impl Executor {
    pub fn new() -> Self {
        Executor
    }
}
```

I implement it and construct my Executor, but the compiler complains: 

```rust
144 |             .serve(app)
    |              ^^^^^ the trait `hyper::common::exec::Executor<hyper::server::conn::spawn_all::NewSvcTask<_, _, _, executor::Executor, hyper::server::conn::spawn_all::NoopWatcher>>` is not implemented for `executor::Executor`
    |
    = help: the following implementations were found:
              <executor::Executor as hyper::common::exec::Executor<std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = ()> + std::marker::Send + 'static)>>>>
    = note: required because of the requirements on the impl of `hyper::common::exec::NewSvcExec<_, _, _, executor::Executor, hyper::server::conn::spawn_all::NoopWatcher>` for `executor::Executor`

error[E0277]: the trait bound `executor::Executor: hyper::common::exec::Executor<hyper::proto::h2::server::H2Stream<_, _>>` is not satisfied
   --> src/app.rs:144:14
    |
144 |             .serve(app)
    |              ^^^^^ the trait `hyper::common::exec::Executor<hyper::proto::h2::server::H2Stream<_, _>>` is not implemented for `executor::Executor`
    |
    = help: the following implementations were found:
              <executor::Executor as hyper::common::exec::Executor<std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = ()> + std::marker::Send + 'static)>>>>
    = note: required because of the requirements on the impl of `hyper::common::exec::H2Exec<_, _>` for `executor::Executor`
```

**Comment by seanmonstar** [comment] 2020-01-27 18:02
You need to make an `Executor` that can spawn any kind of future.

```rust
#[derive(Copy, Clone)]
pub struct Executor;

impl<F> rt::Executor<F> for Executor
where
    F: Future + Send + 'static,
{
    fn execute(&self, fut: F) {
        async_std::task::spawn(fut);
    }
}
```

**Comment by Hexilee** [comment] 2020-01-28 03:12
Thx!

**Comment by Hexilee** [comment] 2020-02-14 02:33
But how to receive an executor as parameter? As `hyper::proto::h2::server::H2Stream<_, _>>` is private.

I try to use template, but...
```rust
fn set_executor<E, F>(executor: E)
where E: rt::Executor<F>,
      F: 'static + Send + Future,
      F::Output: 'static + Send, {}
```
The template parameter type F is unconstrained (it does). I need a concrete trait rt::Executor<F> instead of a trait template.

**Comment by seanmonstar** [comment] 2020-02-17 19:41
It looks like you're trying to expose a new method that internally sets the `Executor`? In that case, that would be a duplicate of https://github.com/hyperium/hyper/issues/1704

**Closed by seanmonstar** 2020-02-17 19:41 UTC
