### ISSUE TITLE
How do I use persistent connections (keepalives) in the client?

### ISSUE THREAD

**Issue by jkleint** [hyperium/hyper#255] opened 2015-01-19 00:09 UTC
Re-using a Client and adding the KeepAlive header doesn't seem to do it.  If this is possible, can anybody share the basic idea or a quick example?

**Comment by seanmonstar** [comment] 2015-01-19 01:56
It's not currently built into the Client. You could do so manually, using
Request and Response. But my next planned feature is a keepalive in the
Client.

**Comment by reem** [comment] 2015-01-19 10:36
Closing as a dupe of #41

**Closed by reem** 2015-01-19 10:36 UTC
Labels: client
