### ISSUE TITLE
`Body` should implement `AsyncRead`

### ISSUE THREAD

**Issue by cramertj** [hyperium/hyper#1364] opened 2017-10-30 18:35 UTC
It seems logical for `Body` to implement the tokio-io [`AsyncRead`](https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncRead.html) trait. Is there a particular reason it does not, or is this just awaiting an implementation?

**Comment by cramertj** [comment] 2017-10-30 22:44
In particular, this is nice when using `tokio_io::io::copy` to copy the body into an `AsyncWrite`. Currently, this looks like:
```rust
res.body().fold(sock, |sock, chunk| {
    tokio_io::io::write_all(sock, chunk).map(|(s, _)| s)
})
```
With `Body: AsyncRead`, you can do:
```rust
tokio_io::io::copy(res.body(), sock)
```

**Comment by seanmonstar** [comment] 2017-10-30 22:55
The reason it doesn't is it can't be done in the type without some overhead, and it'd basically be an adapter of `Stream<Item=impl AsRef<[u8]>>` to `AsyncRead`, which isn't too hyper-specific.

**Comment by cramertj** [comment] 2017-10-30 22:58
> an adapter of  `Stream<Item=impl AsRef<[u8]>>` to `AsyncRead`

Yeah, I guess I'd expect such a thing to exist in some form or another. Do you have any thoughts about how to make these types line up better? The `fold` works, but it's definitely not super intuitive.

**Comment by seanmonstar** [comment] 2017-10-30 23:01
If the other end is a `Sink`, there's `stream.forward(sink)` or `sink.send_all(stream)`...

**Comment by cramertj** [comment] 2017-10-30 23:11
So, what I want then is probably something like `res.body().forward(my_async_rw.framed(bytes()))` where `bytes()` is something like https://github.com/tokio-rs/tokio-io/pull/78 ? Interestingly, even this only works because my `AsyncWrite` also happens to be an `AsyncRead`-- if it wasn't, `framed` wouldn't be available.

**Comment by cramertj** [comment] 2017-10-31 01:30
IMO, even if that works it's far too "plug this thing into this other thing using this thing in the middle". Conceptually, taking a stream which yields some `T: AsRef<[u8]>` and writing it into an `AsyncWrite` seems like it should be fairly straightforward.

**Comment by cramertj** [comment] 2017-11-09 01:09
@seanmonstar In order for the `stream.forward` trick to work, the type has to implement `Sink` with `SinkItem = hyper::Chunk`.

**Comment by seanmonstar** [comment] 2017-12-07 01:35
I'm going to close this for now, because it can't be done without overhead that would affect anyone who didn't need the `AsyncRead` implementation.

**Closed by seanmonstar** 2017-12-07 01:35 UTC

**Comment by cramertj** [comment] 2017-12-07 01:48
@seanmonstar SGTM-- I'll keep this in mind to come back to once alexcrichton/futures-rs#623 is resolved.

**Comment by ry** [comment] 2018-10-23 13:46
@seanmonstar Can you suggest a way to turn a Body into an AsyncRead ?

I guess the reason why there's overhead in presenting Body as an AsyncRead is that Body promises to delivery a "Chunk" - which I infer corresponds to chunks in transfer-encoding: chunked. These chunks are not bounded in length, and so cannot be guaranteed to be written completely into the buffer supplied by `poll_read()` - and therefore it would require internal buffering to present an AsyncRead?  Do I have this right?

If the above is correct, it seems the problem is that Body is too high-level of a concept. It would be desirable to have lower-level body which didn't promise to deliver complete chunks, but just parts of the body as they arrived.

**Comment by seanmonstar** [comment] 2018-10-23 16:34
@ry 

>  I infer corresponds to chunks in transfer-encoding: chunked. [..]  Do I have this right?

No, the `Chunk` type is not actually related to `transfer-encoding: chunked`. (Maybe the name is confusing and should be something else?) A `Chunk` is simply a piece of the body as it arrives. hyper does hardly any buffering (the only buffering is that there needs to be *some* sort of buffer to read at all, and if the headers are smaller than the buffer, or a chunked-encoding body has chunks smaller, than some of the body will still be in the read buffer). Even when chunked encoded, the `Chunk`s are yielded as soon as they are received from the transport.

----

The overhead I was talking about here is around the need for an `impl AsyncRead` to buffer a single `Chunk` at times. This is because you could call `poll_read(buf_with_1kb_space)`, and a `Chunk` from the transport could have been 4kb. In that case, it needs to `poll_data` for a `Chunk`, copy over 1kb, and then save the `Chunk` so the other 3kb can be read.

The [reqwest crate has a `ReadableChunks` type](https://github.com/seanmonstar/reqwest/blob/master/src/async_impl/decoder.rs#L364-L403) that adapts a `Body` into an `AsyncRead`.

**Comment by spease** [comment] 2019-12-16 22:19
It looks like ReadableChunks has been removed from reqwest. What’s the recommended method to expose an AsyncRead trait for the incoming response data now? Thanks.

**Comment by let4be** [comment] 2021-05-29 09:02
It would be really nice to have this in hyper...

**Comment by john-sharratt** [comment] 2021-09-08 19:27
This here seems to work...
https://stackoverflow.com/questions/60964238/how-to-write-a-hyper-response-body-to-a-file

**Comment by john-sharratt** [comment] 2021-09-08 19:31
...and for better efficiency there appears to be this... (but I've not tried it)
https://crates.io/crates/stream-body
