### ISSUE TITLE
Restrict connection to specific IP family (IPv4)

### ISSUE THREAD

**Issue by wbrickner** [hyperium/hyper#2505] opened 2021-04-16 23:46 UTC
Hello,

I'd like to force Hyper to connect to a host only over IPv4.

The API I need to interact with requires me to whitelist IPs, and only accepts IPv4 addresses.
Trying to use the remote API when connected to a VPN works perfectly, but without one my IPv6 address is being used (I think!).

I have scoured the documentation, and can find no way to control the socket / resolution behavior.

Can you help me connect to my host strictly using IPv4?

Thank you.

**Comment by nox** [comment] 2021-04-18 08:35
This is a duplicate of #2418.

**Closed** 2021-04-19 22:20 UTC

**Comment by wbrickner** [comment] 2021-04-20 00:45
For posterity, I solved my issue by writing a wrapper over the DNS resolver.  I am using TLS, so the code is a bit different:

```rust
let client = Client::builder()
      .build::<_, hyper::Body>({
        let mut https = HttpsConnector::new_with_connector({
          let resolver = tower::service_fn(|name| async {
            let mut resolver = GaiResolver::new();
            resolver
              .call(name)
              .await
              .map(|addrs| {
                addrs
                  .filter(|ip| ip.is_ipv4())
                  .into_iter()
              })
          });
          let mut http = HttpConnector::new_with_resolver(resolver);
          http.enforce_http(false);
          http
        });
        https.https_only(true);
        https
      });
```

If you are not using TLS, you can use only the inner implementation:

```rust
HttpConnector::new_with_resolver({
  tower::service_fn(|name| async {
    let mut resolver = GaiResolver::new();
    resolver
      .call(name)
      .await
      .map(|addrs| {
        addrs
          .filter(|ip| ip.is_ipv4())
          .into_iter()
      })
  })
)
```

You can of course flip these both around and use only IPv6 addresses.
