### ISSUE TITLE
Hyper doesn't completely fullfill Expect http1/0 feature

### ISSUE THREAD

**Issue by sterchelen** [hyperium/hyper#2791] opened 2022-03-21 20:52 UTC
Part of  @seanmonstar's communication and his [blog post](https://seanmonstar.com/post/678895803144830976/help-stabilize-hyper-in-curl) about fixing curl tests with hyper enabled, I tried debugging [test357](https://github.com/curl/curl/blob/master/tests/data/test357).

**Version**
Latest version

**Platform**
`SMP PREEMPT Debian 5.16.14-1 (2022-03-15) x86_64 GNU/Linux`

**Description**
* When curl sends an `Expect:100-continue` header and the server responds with a `417` status code, curl repeats the request __without__ an `Expect` header. This is part of the [rfc7231](https://datatracker.ietf.org/doc/html/rfc7231#section-5.1.1)
* Hyper, as soon as it receives something different than the expected `Expect` header, it stops the transaction.

To fix the test357, Hyper should respect the rfc7231.

Here is the point from the rfc7231 about repeating the request without a `Expect:100-continue` header:
```
   o  A client that receives a 417 (Expectation Failed) status code in
      response to a request containing a 100-continue expectation SHOULD
      repeat that request without a 100-continue expectation, since the
      417 response merely indicates that the response chain does not
      support expectations (e.g., it passes through an HTTP/1.0 server).
```
cc @bagder

**Comment by seanmonstar** [comment] 2022-03-21 22:39
Thanks for helping us out, I greatly appreciate this! Ok, let's dig in.

So I read the relevant section in RFC 7231 (thanks for the link!). I understand what the issue is now. I will say, the RFC made the desired outcome somewhat ambiguous, at least to me. It says that a client should retry the request without the header, which makes sense, but it doesn't explicitly say it should do so on the same connection, ignoring the normal HTTP message payload rules. So, I would assume that client would probably do so with a new connection. Otherwise, we're saying that the request, even though it claimed there was a `content-length`, should not count the following bytes as part of the body.

I agree that when thinking about what I just wrote, it seems wasteful to have to open a new connection. But... Do other clients, like web browsers, try to reuse the same connection too? I would worry about intermediaries (proxies and gateways) that disagree on if that `content-length` still counts would result in mismatched (or smuggled) requests.

**Comment by sterchelen** [comment] 2022-03-22 06:20
>  but it doesn't explicitly say it should do so on the same connection, ignoring the normal HTTP message payload rules

Agree

> Do other clients, like web browsers, try to reuse the same connection too?

Good question for web browsers but for curl, here is the output of the test357 with curl's http implementation enabled.
You can see that it reuses the same connection from the initial PUT (the one with the `Expect` header).

As there is nothing stated in the RFC about connection behavior for the repeat handling and that curl reuses the same connection, I would go for the reuse connection solution.
If you are agree, I can implement this change... I would just need some guidance :).


```
20:18:07.341252 == Info: STATE: INIT => CONNECT handle 0x5638760b8f78; line 1834 (connection #-5000)
20:18:07.341327 == Info: Added connection 0. The cache now contains 1 members
20:18:07.341343 == Info: family0 == v4, family1 == v6
20:18:07.341352 == Info:   Trying 127.0.0.1:34243...
20:18:07.341383 == Info: STATE: CONNECT => CONNECTING handle 0x5638760b8f78; line 1895 (connection #0)
20:18:07.341646 == Info: Connected to 127.0.0.1 (127.0.0.1) port 34243 (#0)
20:18:07.341650 == Info: STATE: CONNECTING => PROTOCONNECT handle 0x5638760b8f78; line 2027 (connection #0)
20:18:07.341654 == Info: STATE: PROTOCONNECT => DO handle 0x5638760b8f78; line 2050 (connection #0)
20:18:07.341687 => Send header, 136 bytes (0x88)
0000: PUT /we/want/357 HTTP/1.1
001b: Host: 127.0.0.1:34243
0032: User-Agent: curl/7.83.0-DEV
004f: Accept: */*
005c: Content-Length: 78
0070: Expect: 100-continue
0086: 
20:18:07.341707 == Info: STATE: DO => DID handle 0x5638760b8f78; line 2146 (connection #0)
20:18:07.341712 == Info: STATE: DID => PERFORMING handle 0x5638760b8f78; line 2265 (connection #0)
20:18:07.341930 == Info: Mark bundle as not supporting multiuse
20:18:07.341937 == Info: HTTP 1.1 or later with persistent connection
20:18:07.341940 <= Recv header, 26 bytes (0x1a)
0000: HTTP/1.1 417 OK swsbounce.
20:18:07.341969 <= Recv header, 36 bytes (0x24)
0000: Date: Tue, 09 Nov 2010 14:49:00 GMT.
20:18:07.341977 <= Recv header, 25 bytes (0x19)
0000: Server: test-server/fake.
20:18:07.341983 <= Recv header, 18 bytes (0x12)
0000: Content-Length: 0.
20:18:07.341989 == Info: Got 417 while waiting for a 100
20:18:07.341993 <= Recv header, 1 bytes (0x1)
0000: .
20:18:07.341998 == Info: multi_done: status: 0 prem: 0 done: 0
20:18:07.342087 == Info: Connection #0 to host 127.0.0.1 left intact
20:18:07.342113 == Info: Issue another request to this URL: 'http://127.0.0.1:34243/we/want/357'
20:18:07.342123 == Info: STATE: PERFORMING => CONNECT handle 0x5638760b8f78; line 2441 (connection #-5000)
20:18:07.342167 == Info: Found bundle for host 127.0.0.1: 0x5638760b4438 [serially]
20:18:07.342180 == Info: Re-using existing connection! (#0) with host 127.0.0.1
20:18:07.342184 == Info: Connected to 127.0.0.1 (127.0.0.1) port 34243 (#0)
20:18:07.342188 == Info: STATE: CONNECT => DO handle 0x5638760b8f78; line 1888 (connection #0)
20:18:07.342212 => Send header, 114 bytes (0x72)
0000: PUT /we/want/357 HTTP/1.1
001b: Host: 127.0.0.1:34243
0032: User-Agent: curl/7.83.0-DEV
004f: Accept: */*
005c: Content-Length: 78
0070: 
20:18:07.342227 == Info: STATE: DO => DID handle 0x5638760b8f78; line 2146 (connection #0)
20:18:07.342231 == Info: STATE: DID => PERFORMING handle 0x5638760b8f78; line 2265 (connection #0)
20:18:07.342246 => Send data, 78 bytes (0x4e)
```

**Comment by bagder** [comment] 2022-03-22 07:48
HTTP (since 1.1) allows the connection to be reused everywhere unless explicitly told not to and as long as the "data flow" is in a known idle state (ie there is nothing left pending to handle from the previous request). A new request is a new start, HTTP is "stateless" (let's pretend NTLM doesn't exist).

**Comment by seanmonstar** [comment] 2022-03-25 23:25
I should have been more clear what I meant. I didn't mean the state should carry after a message is done. But rather that, as you refer to it, I don't believe the connection is in an idle state, the request body was never finished. But I wanted to do some more research as well, and I'm back.

It seems `Expect: 100-continue` is not used very much. MDN says browsers don't use it, but explicitly says curl does. When checking other libraries, some have basic support, but they didn't seem handle 417 responses either. So, I imagine that beyond curl, this is not explored a whole lot more. Now, I could be wrong, but I have strong suspicions that the way curl is sending a second request could greatly confuse proxies. RFC 7231 says that a client should retry the request, but makes no mention that the returned 417 response means the request body framing is treated differently. So, a proxy who didn't know anything about 417 (and others who interpret the spec as I'm doing) would understand this very differently:

```
PUT /we/want/357 HTTP/1.1
Host: 1.2.3.4:1234
Expect: 100-continue
Content-Length: 58

POST /evil HTTP/1.1
Host: localhost:1234
Content-Length: 0

```

Just because the first request received a 417, the following 58 bytes are part of the request body. If a backend proxy interprets the request bytes the other way, then it looks like 2 different requests.

If the response doesn't expect to read the rest of the body, it needs to close the connection. The client cannot use that open connection to start a new request until the body had been sent, so it will likely need to close it and start a new one.

**Comment by seanmonstar** [comment] 2022-05-23 16:59
Looks like this was solved in curl in this PR: https://github.com/curl/curl/pull/8811/files

**Closed by seanmonstar** 2022-05-23 16:59 UTC
Labels: S-bug
