### ISSUE TITLE
checking ContentType 

### ISSUE THREAD

**Issue by yfery** [hyperium/hyper#1222] opened 2017-06-19 09:19 UTC
I use Hyper 0.11, Mime 0.3.2 and Hyper-tls 0.1.0

I want to do actions based on ContentType 

```
use hyper::Client;
use hyper::header::ContentType;
...
let mut core = ::tokio_core::reactor::Core::new().unwrap();
let client = ::hyper::Client::configure()   
  .connector(::hyper_tls::HttpsConnector::new(4, &core.handle()).unwrap())
  .build(&core.handle());

let mut work = client.get(subscription.url.parse().unwrap()).and_then(|res| {
  match res.headers().get() {
    Some(&ContentType(mime::TEXT_XML)) => (),
    None => ()
  }
  res.body().for_each(|chunk| { 
    io::stdout().write_all(&chunk).map(|_| ()).map_err(From::from) 
  }) 
});    
core.run(work).unwrap();
```
This error is raised:

```
error: to use a constant of type `mime::Mime` in a pattern, `mime::Mime` must be annotated with `#[derive(PartialEq, Eq)]`
   --> src/main.rs:187:39
    |
187 |                     Some(&ContentType(mime::TEXT_XML)) => (),
    |                                       ^^^^^^^^^^^^^^
    |
    = note: #[deny(illegal_struct_or_enum_constant_pattern)] on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #36891 <https://github.com/rust-lang/rust/issues/36891>
```

mime struct miss the derive annotation or did I use it wrongly ?

**Comment by seanmonstar** [comment] 2017-06-19 16:19
The `Mime` type is not able to `derive(PartialEq)`, and so constants of it cannot be used as patterns in match statements. You could use `if headers.get() == Some(&ContentType(mime::TEXT_XML)) { ... }`.

Being a usage question, and not a bug/issue, I'm going to close this.

**Closed by seanmonstar** 2017-06-19 16:19 UTC
