### ISSUE TITLE
entered unreachable code

### ISSUE THREAD

**Issue by x1957** [hyperium/hyper#2021] opened 2019-11-21 16:01 UTC
```
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: thread '<unnamed>' panicked at 'internal error: entered unreachable code', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.0-alpha.4/src/client/pool.rs:659:42
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: stack backtrace:
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 0:     0x55cb604bfb24 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 1:     0x55cb604bfb24 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 2:     0x55cb604bfb24 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/sys_common/backtrace.rs:76
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 3:     0x55cb604bfb24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/sys_common/backtrace.rs:60
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 4:     0x55cb604e1d2c - core::fmt::write::h01edf6dd68a42c9c
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libcore/fmt/mod.rs:1030
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 5:     0x55cb604bb507 - std::io::Write::write_fmt::hf15985f193f03c04
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/io/mod.rs:1412
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 6:     0x55cb604c1ff5 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/sys_common/backtrace.rs:64
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 7:     0x55cb604c1ff5 - std::sys_common::backtrace::print::hf89a79e3921a2366
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/sys_common/backtrace.rs:49
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 8:     0x55cb604c1ff5 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/panicking.rs:196
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 9:     0x55cb604c1ce6 - std::panicking::default_hook::h8f803b0bc31a5c37
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/panicking.rs:210
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 10:     0x55cb604c26f5 - std::panicking::rust_panic_with_hook::h825f041245da8739
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/panicking.rs:473
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 11:     0x55cb603c4f75 - std::panicking::begin_panic::h65f7798d40eb530e
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 12:     0x55cb603ad44f - <hyper::client::pool::Checkout<T> as core::future::future::Future>::poll::hc289d312474d2939
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 13:     0x55cb603c1f8b - <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll::h768c00b32bb70f45
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 14:     0x55cb6037d9bd - futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::heb94ee34b43e5c82
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 15:     0x55cb603e5370 - futures_util::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll::h27aa060ac3edce56
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 16:     0x55cb6039542e - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hbde0d9dca6f8acba
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 17:     0x55cb60423291 - <hyper::client::ResponseFuture as core::future::future::Future>::poll::hde048b013cf320a4
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 18:     0x55cb6036f079 - <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll::h049001c9457ab501
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 19:     0x55cb6036ef40 - <reqwest::async_impl::client::Pending as core::future::future::Future>::poll::h71ba1c19fce6ff05
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 20:     0x55cb601fa649 - <std::future::GenFuture<T> as core::future::future::Future>::poll::he5b6f7edda3df620
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 21:     0x55cb601f3b6b - tokio_executor::enter::Enter::block_on::h09dcb573323e0a7a
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 22:     0x55cb601f2266 - tracing_core::dispatcher::with_default::h9cd7e8a51e6c6d19
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 23:     0x55cb601f584f - std::thread::local::LocalKey<T>::with::h1663161e4d7cf96c
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 24:     0x55cb601efa7b - tokio::runtime::threadpool::Runtime::block_on::h15edf3b97d03a727
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 25:     0x55cb601e98cc - <F as threadpool::FnBox>::call_box::h548a9633f619736c
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 26:     0x55cb6028cd41 - std::sys_common::backtrace::__rust_begin_short_backtrace::h384eff2f39aba819
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 27:     0x55cb604c645a - __rust_maybe_catch_panic
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libpanic_unwind/lib.rs:80
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 28:     0x55cb6028d328 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hba402e7c2e74d859
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 29:     0x55cb604b5d1f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 30:     0x55cb604c57d0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 31:     0x55cb604c57d0 - std::sys_common::thread::start_thread::h557b0c2dc4449562
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/sys_common/thread.rs:13
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 32:     0x55cb604c57d0 - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: at src/libstd/sys/unix/thread.rs:79
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 33:     0x7f4719ba940b - start_thread
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 34:     0x7f47196cde7f - __GI___clone
11月 21 23:53:26 ip-172-31-34-47.ap-northeast-1.compute.internal tracer[26093]: 35:                0x0 - <unknown>
```

**Comment by sfackler** [comment] 2019-11-21 16:05
It looks like this may have already been fixed on master:

https://github.com/hyperium/hyper/blob/v0.13.0-alpha.4/src/client/pool.rs#L644-L662
vs
https://github.com/hyperium/hyper/blob/131962c86ab0a31c2413261cf4532eca88d67dcb/src/client/pool.rs#L646-L664

**Comment by sfackler** [comment] 2019-11-21 16:05
Yep, duplicate of https://github.com/hyperium/hyper/issues/1996.

**Closed by sfackler** 2019-11-21 16:05 UTC
