### ISSUE TITLE
method POST with body-raw incorrect work buffer in server with request

### ISSUE THREAD

**Issue by sapsan4eg** [hyperium/hyper#967] opened 2016-12-04 09:57 UTC
Hi guys, i have problem when i send POST with body-raw to my server. First request work fine, but following requests with same data will wrong parsing. If the difference is **less than a second** between requests. The method is added to the body-raw.
For example, this for second and following requests print to console: `{"mydata":"the data that I sent"}}POST`
```
#![deny(warnings)]
extern crate hyper;
extern crate env_logger;

use hyper::server::{Request, Response};

static PHRASE: &'static [u8] = b"Hello World!";

fn hello(req: Request, res: Response) {
    println!("{}", req.method);
    res.send(PHRASE).unwrap();
}

fn main() {
    env_logger::init().unwrap();
    let _listening = hyper::Server::http("127.0.0.1:3000").unwrap()
        .handle(hello);
    println!("Listening on http://127.0.0.1:3000");
}
```

**Comment by rpjohnst** [comment] 2016-12-08 23:00
This looks like a duplicate of #309

**Comment by sapsan4eg** [comment] 2016-12-09 12:13
That issue was closed but not soled. As I understand it the only way out is to move to 0.10. But the release has not yet been. And 0.9x is not compatible with 0.10. And this does not solve the current problem with 0.9x.

**Comment by rpjohnst** [comment] 2016-12-10 05:27
The workaround for 0.9.x is to make sure that either 1) the entire request body is read, or 2) that the connection is closed after handling the request.

**Comment by seanmonstar** [comment] 2017-01-17 01:38
Closing as duplicate of #309.

**Closed by seanmonstar** 2017-01-17 01:38 UTC
