### ISSUE TITLE
HTTP2-only Server sends preface to HTTP1 requests

### ISSUE THREAD

**Issue by sanmai-NL** [hyperium/hyper#1630] opened 2018-08-10 15:24 UTC
Take this (incomplete but clear enough) sample code (v0.12.7):

```rust
let tcp = TcpListener::bind(&socketaddr).unwrap();
let tls = tcp
    .incoming()
    .and_then(|s| serverconfig.accept_async(s))
    .then(|r| match r {
        Ok(x) => Ok::<_, io::Error>(Some(x)),
        Err(error) => {
            warn!("Client connection error: {}", error);
            Ok(None)
        }
    }).filter_map(|x| x);
let fut = Server::builder(tls)
    //.http2_only(true)
    .http1_only(true)
    .serve(move || service_fn(producer.clone()));
let mut core = tokio_core::reactor::Core::new().unwrap();
if let Err(err) = core.run(fut) {
    error!("FATAL: {}", err);
    panic!()
}
Ok(())
```

Multiple `curl` invocations (e.g., `--no-alpn`, `--http2`, `--http2-prior-knowledge`) seem to show the same logic is applied no matter what. Both HTTP 1.1 and 2 are supported.

**Comment by seanmonstar** [comment] 2018-08-10 18:13
Hm, I'm trying to reproduce, but setting `http1_only(true)` and then sending an HTTP2 request seems to be erroring, as expected...

**Comment by seanmonstar** [comment] 2018-08-13 16:40
Ah, hyper doesn't know anything about ALPN, you'd need to configure that in the TLS acceptor. The options in hyper are telling it what protocols to allow internally. The default is that if the transport sends HTTP/1 or HTTP/2 (after any decrypting or whatever the transport may do), it just works. The `http{1,2}_only()` methods are there in case for some reason you would rather that hyper tear down the connection if the protocol is different.

**Comment by sanmai-NL** [comment] 2018-08-13 17:01
Thanks, I fixed the ALPN issue.

With rustls ALPN configured to accept `h2` and `http1.1`, `http2_only(true)`, some kind of corrupt response data are sent:

```
  curl --http1.1 --location -k -v https://localhost.localdomain:8082/ | hexdump
* Uses proxy env variable no_proxy == '127.0.0.1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,::1,fd00::/8, localhost,.localdomain'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost.localdomain (::1) port 8082 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [216 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [89 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [5058 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=testserver.com
*  start date: Aug 13 16:07:04 2016 GMT
*  expire date: Feb  3 16:07:04 2022 GMT
*  issuer: CN=ponytown RSA level 2 intermediate
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
} [5 bytes data]
> GET / HTTP/1.1
> Host: localhost.localdomain:8082
> User-Agent: curl/7.61.0
> Accept: */*
> 
{ [5 bytes data]
100     9    0     9    0     0    529      0 --:--:-- --:--:-- --:--:--   529
* Connection #0 to host localhost.localdomain left intact
0000000 0000 0400 0000 0000 0000               
0000009
```

**Comment by seanmonstar** [comment] 2018-08-13 17:06
Those bytes look a lot like the initial `SETTINGS` frame an HTTP2 server would respond with...

**Comment by sanmai-NL** [comment] 2018-08-13 17:07
> and then sending an HTTP2 request seems to be erroring, as expected...
So, it comes down to what erroring means here?

**Comment by seanmonstar** [comment] 2018-08-13 17:11
> So, it comes down to what erroring means here?

Perhaps! Do you have a suggestion on what should be changed here?

**Comment by sanmai-NL** [comment] 2018-08-13 17:13
If a request comes in with an incompatible HTTP version specified, `hyper` should close the connection?

**Comment by seanmonstar** [comment] 2018-08-13 17:54
I agree with that. So, it seems the issue in this case is that if the client sends a HTTP/1 request, and hyper is told to only use HTTP/2, hyper will actually write the HTTP2 `SETTINGS` frame before realizing that incoming bytes weren't HTTP2. Does that sound right?

**Comment by sanmai-NL** [comment] 2018-08-13 18:14
To me it does. (But I haven’t spent the time to dig into this issue to give you any more confirmation/knowledge than you already have.)

**Comment by AlexDvorak** [comment] 2018-10-08 18:45
@sanmai-NL could you post the full test script?

**Comment by sanmai-NL** [comment] 2018-10-09 14:56
@AlexDvorak: I didn’t have one really, it’s just a `curl` invocation.

**Comment by seanmonstar** [comment] 2018-10-18 21:49
So the behavior seen here is happening in the `h2` dependency. It's currently setup to first flush the server preface, and then read the client preface. This means the HTTP2 preface would be written to every connection here, without checking if it sent an HTTP2 preface itself.

If worth fixing, it'd just require swapping the order in `h2`. I'm going to close this here in hyper as there's nothing hyper itself can do, besides peeking for a preface before handing off to `h2`.

**Closed by seanmonstar** 2018-10-18 21:49 UTC
Labels: A-http2, A-server, B-upstream
