### ISSUE TITLE
Accept header drops */* MIMEs

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#885] opened 2016-08-08 18:15 UTC

**Comment by seanmonstar** [comment] 2017-03-16 02:12
This should be fixed in mime@0.2.3. Just running `cargo update -p mime` should be enough. Sorry for taking so long on this.

**Comment by seanmonstar** [comment] 2017-03-16 02:40
I just ran some updated tests in hyper and confirmed that this is fixed. Since there is no needed code to change in hyper, I'm going to close without a PR.

**Closed by seanmonstar** 2017-03-16 02:40 UTC
Labels: bug, headers, upstream

**Comment by sfackler** [comment] 2017-03-16 03:02
Awesome thanks!
