### ISSUE TITLE
Mixing sync and async IO

### ISSUE THREAD

**Issue by alexjg** [hyperium/hyper#1165] opened 2017-05-07 11:29 UTC
I've just started having a play with the tokio based async Hyper on `master` and have a simple question. As I understand things `Service.call` should return a future immediately without blocking. However, the implementation of the server I'm working on has a bunch of synchronous code that interacts with a database, it looks like I should set up something like a threadpool to do that work on and return futures executing on that threadpool, is that the correct? That feels like a strange approach but I think that's probably just because there aren't yet async interfaces for things like Diesel available yet?

**Comment by seanmonstar** [comment] 2017-05-08 23:44
Yes what you describe is exactly the correct approach. If you have things that would block a thread, you should run them in a  different thread. For example, if you look at nodejs, its file operations (`fs.readFile` and etc) are all executed on a thread pool, and the results sent back to the event loop thread.

Closing as a usage question, and not a bug with hyper.

**Closed by seanmonstar** 2017-05-08 23:44 UTC

**Comment by suyanlong** [comment] 2017-08-03 06:23
i want know ,how send  result to the event loop thread???
