### ISSUE TITLE
Access to the API from C?

### ISSUE THREAD

**Issue by bagder** [hyperium/hyper#2265] opened 2020-08-11 15:16 UTC
If a C program would like to use hyper for h1/h2, is there a C API offered?

**Comment by seanmonstar** [comment] 2020-08-11 15:36
In short, there isn't *yet* an API, largely because no one has shown significant interest that one be provided.

I'm interested to hear more of the use case that you're thinking of.

**Comment by bagder** [comment] 2020-08-11 22:20
I have networking code written in plain old C that is used, well let's say "widely" and it isn't an understatement - let's call it curl. I'm right now researching the feasibility of switching over to using hyper for the the HTTP/1 and HTTP/2 handling parts. For this to work, I would need a C based API that's sensible and stable going forward. A plausible first step to ponder on: optionally (as a build-time option) replace nghttp2 with hyper for HTTP/2.

I was primarily curious if I had missed an existing such API but I now realize I hadn't. I also understand that you possibly don't want to do this for me and my single (still "theoretical") use case, but maybe I'm not alone.

**Comment by seanmonstar** [comment] 2020-08-12 00:17
Yea, I knew you from curl, just didn't want to assume what you might want to do :)

I've thought about exposing a C API a bunch of times, but hadn't had anyone really ask, so I could only guess at interest. I'm happy to help figure this out, though! We could probably spec out some `hyper_c` crate that provides a stable C API. Would you be looking to plug in to your own event loop? hyper currently accepts custom read and write objects, and they can provide their own way to notify hyper when IO is ready again. Of course, if not needing to use your own event loop, we could probably expose less internals, but 🤷 .

Can I also ask how "interested" you are? Are you just exploring what things look like? Do you have a deadline you'd hope to have this "theoretical" stuff in curl? Do you think you or others would be able to contribute to building hyper C bindings?

Knowing these things would help me put together a proposal. 😀

**Comment by bagder** [comment] 2020-08-12 09:21
I would definitely need my own event loop (libcurl itself is event loop agnostic and allows apps to use what they want).

On the level of my interest: it's a little of a chicken and egg problem. If the API is "suitable enough" I'm very interested, as in I'm probably getting funding to work on this project. It's not a done deal though and there's no deadline at all at this point. Right now, without even an API to look at and think about, the project is not feasible at all (as I don't consider myself qualified enough to work effectively on the hyper side of the puzzle)

I of course also have challenges of my own on "my side" of things that may or may not put obstacles in the way independently of your project and C API. I'm not trying to suggest that this just is all just waiting for a C API as the only bump in the road.

I don't even think I yet have a fair grasp of what exactly I would want the API to look like even if I would dream up my ideal API. Early days still. Dipping toes.

> Do you think you or others would be able to contribute to building hyper C bindings?

I will certainly join in and do my part - if nothing else for entirely selfish reasons so that the bindings end up as good as possible for my intended use case. After all, I have some experience in making and offering C APIs. I haven't actually asked around anywhere so I don't know what level of interest we can hope for from others.

**Comment by seanmonstar** [comment] 2020-08-13 20:21
OK, so I'm working on a draft for a header file (`hyper.h` or whatever). Does that seem useful in your evaluation?

So far the basic stuff is pretty straight forward, requests, responses, headers, the client. The more complex thing to represent I feel is a [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html), which in Rust, `client.send(req)` returns a `Future<Output = Result<Response, Error>>`. Futures in Rust have a single `poll` method, and a user calls that to do work, along with a `Waker` argument. `poll` either returns the `Output`, or `Pending` to say it would need to be polled again at a later time. When it is `Pending`, it will have stored the `Waker` somewhere to signal when more work could happen.

In hyper, it's typical that IO is the reason the `Future` couldn't progress. Internally, it will have called `poll_read(waker, buf)`, and it's assumed that the IO type will register with something (such as epoll), and when ready again, it'd call `waker.wake()`. That would signal the top future to try again.

When looking in curl, there seems to be some similar concepts in the multi API. It looks like you collect together these transfers into a `CURLM`, the user waits on epoll (or select or whatever), and then calls `curl_multi_perform` to make more progress. From a cursory reading, the simpler version will just re-poll *all* the transfers, and `curl_multi_socket_action` can be used when you have a larger number of sockets and don't want to try *all* transfer on ever poll, just the ones that are ready.

The last wrinkle is that in Rust `Future`s can have different output types, and in hyper, there are potentially a couple of extra "background" futures (so `Future<Output = ()>`) that the user would need to also poll. I think we can easily provide a `hyper_task_pool` that you push these futures into that knows which ones to poll. The wrinkle is that some resolve to `()` (C's `void`), and some to a `Response`. So, the `hyper_task` would need some way to check what return type it has, and pull that out. I suppose that could be a simple internal `union`...

**Comment by laudiacay** [comment] 2020-08-14 01:46
Hi, someone I know directed me to this issue- I've done some rust work in the past and am interested in contributing if you think I could be useful. 

Just wondering- were y'all considering bindgen at all?

**Comment by bagder** [comment] 2020-08-14 08:46
libcurl provides a "multi" API that performs any amount of parallel transfers within the same thread. It exists in two flavors, one that assumes the use of select() and one that lets the user plug-in and use their own event system - the latter for better scaling and performance when moving up in the thousands of simultaneous connections. We have users with libevent, libev, libuv, plain epoll and virtually every other known event-based system.

So for curl it is important that support libraries are single-threaded (at least appearing so) and non-blocking.

A typical non-blocking behavior for us, and perhaps one that you could mimic with your Futures, is to offer information in an API about how to poll it for completeness (like are we waiting for READ and/or WRITE on a socket) and/or a timeout when it should get polled even if no event has been detected. The the curl event loop just polls the socket waiting for a trigger event or a timeout, and only if one of those happens it calls the library that then performs whatever it needs needs to do - and can then update the next "waiting conditions".

**Comment by seanmonstar** [comment] 2020-08-19 01:35
I'm not done yet, but I've made some progress and pushed it into this branch here: https://github.com/hyperium/hyper/tree/hyper-capi

Some relevant pieces:

- The header file: https://github.com/hyperium/hyper/blob/hyper-capi/hyper-capi/include/hyper.h
- A client example: https://github.com/hyperium/hyper/blob/hyper-capi/hyper-capi/examples/client.c

It doesn't work yet, but does show how the API mostly looks. There's a `hyper_io` type, which shows how the callbacks work. There's a `hyper_executor` and `hyper_task`, for polling async tasks/futures. There's only a few pieces of the header file missing, and then of course the actual code for the headers will be needed.

**Comment by seanmonstar** [comment] 2020-09-09 20:06
To aid with reviewing of the design, I've turned the branch into a pull request (https://github.com/hyperium/hyper/pull/2278). I hope to make it more usable over the next couple weeks.

**Comment by DemiMarie** [comment] 2020-09-15 22:52
Some of my own comments:

- libcurl handles OOM by returning an error, while Rust libraries typically abort in this case.
- Rust libraries often have larger code size than their C counterparts.
- I believe that libcurl is often used in embedded environments, where OOM is quite common, and where code size is often a significant limitation.

I would love to see Rust used in libcurl, but I also don’t want it to be a regression for libcurl’s users.  If hyper could recover from OOM and have code size comparable to the C code it replaces, I would consider that a major advance for both hyper and the Rust ecosystem in general.

**Comment by bagder** [comment] 2020-09-16 06:07
> Rust libraries typically abort in this case.

I had no idea. That's a horrible way to deal with problems and not the decision to make for system libraries.

Is that what hyper does too? If so, it'll be a concern.

> I would love to see Rust used in libcurl, but I also don’t want it to be a regression for libcurl’s users.

I completely and wholeheartedly agree, and in fact you can consider me (as lead developer in the curl project) signed up on the mission to see us move on both these items. Put simply: Hyper cannot be a transparent and good choice for libcurl until it can be used in a way that doesn't cause any notable regressions or issues. The job set out here is thus done until we're there.

Regarding code size and curl being used in different environments etc: that is indeed true and we should not presume that all users want or can go with Rust solutions - not even when when/if we can make them used completely transparently. curl has been used on over 70 operating systems on 20 different CPU architectures. It is quite simply much more portable and versatile than Rust is. The idea from my end is to make curl to *optionally* use Hyper as a backend (selected at build-time).

**Comment by XAMPPRocky** [comment] 2020-09-16 08:24
> I had no idea. That's a horrible way to deal with problems and not the decision to make for system libraries.
> 
> Is that what hyper does too? If so, it'll be a concern.

It's the default behaviour, but you can override it, this would just need to be exposed somehow in the hyper C API. The API is not currently stable, so you have to use a nightly Rust compiler.

- [`std::alloc::set_alloc_error_hook`](https://doc.rust-lang.org/stable/std/alloc/fn.set_alloc_error_hook.html)

**Comment by bagder** [comment] 2020-09-16 08:31
> this would just need to be exposed somehow in the hyper C API

Sure, if you think that's a valuable feature to expose. I would be fine with just making the C API always return error on errors...

**Comment by XAMPPRocky** [comment] 2020-09-16 08:55
Sorry, maybe exposed was the wrong word. It totally could be just an error when you’re using the API. I more meant that there would need to be a function to set the override hook, see the below example.

```
#[no_mangle]
pub unsafe extern "C" fn unset_alloc_abort() {
    std::alloc::set_alloc_error_hook(|_| panic!(“alloc error”));
}

#[repr(C)] struct Foo;

#[no_mangle]
pub unsafe extern "C" fn new_foo() -> *mut Foo {
    catch_unwind(|| {
        // Allocations
        Box::into_raw(Box::new(Foo))
    }).unwrap_or(std::ptr::null_mut())
}
```

**Comment by a1phyr** [comment] 2020-09-16 09:33
Catching panics is not only nice for OOM error handling, but it is necessary anyway as [panicking across FFI boundaries is UB](https://doc.rust-lang.org/nomicon/ffi.html#ffi-and-panics).

**Comment by mitsuhiko** [comment] 2020-09-16 10:29
The other more insane version could be to longjump out of the error hook.

**Comment by bagder** [comment] 2020-09-16 11:25
you still want the library to not leak memory or any other resources, even in the OOM situation, so simply "jumping" out of it is rarely the best idea - said without having a clue about the Hyper internals.

**Comment by xfix** [comment] 2020-09-16 11:36
Currently Rust standard library doesn't attempt to handle OOM (for instance, `Vec::push` may fail in a way that cannot be handled. [RFC 2116](https://rust-lang.github.io/rfcs/2116-alloc-me-maybe.html) does provide a way to handle allocation failures on standard library collections, but so far it's nightly-only.

**Comment by DemiMarie** [comment] 2020-09-16 15:08
Personally, I don’t believe we should rely on unwinding to handle OOM errors.  The devices which have the greatest need to recover from OOM are also the ones where the code size overhead of unwinding is the greatest concern.  I greatly prefer the Zig approach, where any function that takes an allocator is passed one explicitly, and where running out of memory is just another error.  Maybe I will write an RFC for that someday.

**Comment by bagder** [comment] 2020-09-17 07:36
>  The devices which have the greatest need to recover from OOM are also the ones where the code size overhead of unwinding is the greatest concern

I strongly disagree. A system library, any system library, has the obligation to clean up after itself. **In all and any circumstances**. If a library function call fails, it needs to return an error and it it needs to **never** leak memory whatever error happened. Applications using these libraries should be able to depend on that, and if the application thinks a memory error, or any other serious error, being returned from said library is a show-stopper then *the application can decide to abort or exit*. It is not the choice to make for the library. It never is.

This gets even more emphasized if a library (like Hyper) is used by another library (like libcurl), where this second library thinks of this behavior and "rock solidness" to be something to be proud of and is even pushed as a "selling point" to users, and if the sub-library then cannot deliver on this promise then libcurl cannot either and then: :disappointed:

**Comment by jplatte** [comment] 2020-09-17 08:39
@badger the comment you replied to did not advocate for the library handling OOMs itself (by exiting, aborting or whatever), just for catching OOMs without unwinding. This would require use of data types with fallible allocation built-in, which is not yet the case for Rust's `std` types (but that is being worked on IIRC).

**Comment by bagder** [comment] 2020-09-17 08:44
@jplatte Thanks for clarifying that for me!

**Comment by DemiMarie** [comment] 2020-09-17 15:56
@bagder No offence taken.  Your comment is one of the best arguments I have seen as to why OOM should *not* be a fatal error, even though much code and even some system libraries (glib, macOS’s Cocoa, librsvg, cmark, gumbo) considers it to be such.  Ironically, I believe that Rust, due to its memory safety and automatic resource cleanup, is in a *better* position than C to recover from OOM errors, once libstd is updated to provide fallible allocation.

**Comment by seanmonstar** [comment] 2020-09-17 21:26
> `std::alloc::set_alloc_error_hook`

I've just tried some experiments, and it indeed works just fine to do some `panic!(HyperOom)` and then be able to catch that in `hyper-capi`, just returning a null pointer. The only issue to me there is with it being a nightly-only feature. The tracking issue hasn't seen much traffic, maybe stabilizing it can done soon?


> I would be fine with just making the C API always return error on errors...

I think it needs to be part of hyper's C API, since it requires setting a global (Rust's alloc error hook), and it'd be problematic if different libraries all try to set that automatically.

**Comment by DemiMarie** [comment] 2020-09-17 21:47
I think we really need a Rust RFC that makes the default hook panic.

**Comment by leo60228** [comment] 2020-09-22 18:55
Unwinding in OOM is undefined behavior, as `alloc::alloc::handle_alloc_error` is marked as `#[rustc_allocator_nounwind]`.

**Comment by RalfJung** [comment] 2020-10-09 09:02
> Unwinding in OOM is undefined behavior, as `alloc::alloc::handle_alloc_error` is marked as `#[rustc_allocator_nounwind]`.

That attribute is going away together with the "panic" default hook: https://github.com/rust-lang/rust/pull/76448.

**Comment by seanmonstar** [comment] 2021-01-12 23:36
With the merge of #2278, I've opened some new issues that are more fine grained (in the [A-ffi label](https://github.com/hyperium/hyper/labels/A-ffi)), and so I think this can be closed as "done".

**Closed by seanmonstar** 2021-01-12 23:36 UTC
Labels: A-ffi, E-hard, S-feature
