### ISSUE TITLE
Openssl::with_cert_and_key certificate verification

### ISSUE THREAD

**Issue by jimmycuadra** [hyperium/hyper#752] opened 2016-03-29 06:21 UTC
I noticed that `Openssl::with_cert_and_key` [disables certificate verification](https://github.com/hyperium/hyper/blob/7c76fff3aaf0f0a300e76622acb56eaf1e2cb474/src/net.rs#L624), shown below for convenience:

``` rust
pub fn with_cert_and_key<C, K>(cert: C, key: K) -> Result<Openssl, SslError>
where C: AsRef<Path>, K: AsRef<Path> {
    let mut ctx = try!(SslContext::new(SslMethod::Sslv23));
    try!(ctx.set_cipher_list("DEFAULT"));
    try!(ctx.set_certificate_file(cert.as_ref(), X509FileType::PEM));
    try!(ctx.set_private_key_file(key.as_ref(), X509FileType::PEM));
    ctx.set_verify(SSL_VERIFY_NONE, None);
    Ok(Openssl { context: Arc::new(ctx) })
}
```

I'm guessing this is done because the expected use is for a server accepting connections from clients without client certificates. However, if someone uses this method for setting up a client to present a client certificate to a server, this will disable verification of the server's certificate.

Is my understanding here correct? If so, I think there should be two separate methods depending on whether it's intended for client or server use. At the very least, the documentation for the current method should make it very clear that it's not safe to use on the client side when using client certificates.

**Comment by seanmonstar** [comment] 2016-03-29 17:14
Yes, your guess is correct. I assumed most people wanting an easy constructor with a cert and key were using it for a server, not a client.

**Comment by frewsxcv** [comment] 2016-04-06 04:33
Related to https://github.com/hyperium/hyper/issues/472

**Comment by frewsxcv** [comment] 2016-04-17 21:50
> If so, I think there should be two separate methods depending on whether it's intended for client or server use.

Ever since https://github.com/hyperium/hyper/pull/757, there are now separate traits for server and client TLS use. That said, there still needs to exist a crate that actually verifies the certificates for this to be completed.

In my opinion, this issue can be closed as a duplicate of  https://github.com/hyperium/hyper/issues/472.

**Comment by jimmycuadra** [comment] 2016-04-17 22:32
Isn't hostname verification different the certificate verification?

**Comment by sfackler** [comment] 2017-01-15 07:00
The ssl feature has been removed, so I believe this issue can be closed.

**Comment by seanmonstar** [comment] 2017-01-15 07:24
Indeed, SSL was removed, see #985.

**Closed by seanmonstar** 2017-01-15 07:24 UTC
